/*
 * This file is generated by jOOQ.
 */
package database.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Appointments implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String patientName;
    private LocalDateTime dateTime;
    private String doctorName;
    private Boolean deleated;

    public Appointments() {}

    public Appointments(Appointments value) {
        this.id = value.id;
        this.patientName = value.patientName;
        this.dateTime = value.dateTime;
        this.doctorName = value.doctorName;
        this.deleated = value.deleated;
    }

    public Appointments(
        Integer id,
        String patientName,
        LocalDateTime dateTime,
        String doctorName,
        Boolean deleated
    ) {
        this.id = id;
        this.patientName = patientName;
        this.dateTime = dateTime;
        this.doctorName = doctorName;
        this.deleated = deleated;
    }

    /**
     * Getter for <code>appointments.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>appointments.id</code>.
     */
    public Appointments setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>appointments.patient_name</code>.
     */
    public String getPatientName() {
        return this.patientName;
    }

    /**
     * Setter for <code>appointments.patient_name</code>.
     */
    public Appointments setPatientName(String patientName) {
        this.patientName = patientName;
        return this;
    }

    /**
     * Getter for <code>appointments.date_time</code>.
     */
    public LocalDateTime getDateTime() {
        return this.dateTime;
    }

    /**
     * Setter for <code>appointments.date_time</code>.
     */
    public Appointments setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
        return this;
    }

    /**
     * Getter for <code>appointments.doctor_name</code>.
     */
    public String getDoctorName() {
        return this.doctorName;
    }

    /**
     * Setter for <code>appointments.doctor_name</code>.
     */
    public Appointments setDoctorName(String doctorName) {
        this.doctorName = doctorName;
        return this;
    }

    /**
     * Getter for <code>appointments.deleated</code>.
     */
    public Boolean getDeleated() {
        return this.deleated;
    }

    /**
     * Setter for <code>appointments.deleated</code>.
     */
    public Appointments setDeleated(Boolean deleated) {
        this.deleated = deleated;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Appointments other = (Appointments) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.patientName == null) {
            if (other.patientName != null)
                return false;
        }
        else if (!this.patientName.equals(other.patientName))
            return false;
        if (this.dateTime == null) {
            if (other.dateTime != null)
                return false;
        }
        else if (!this.dateTime.equals(other.dateTime))
            return false;
        if (this.doctorName == null) {
            if (other.doctorName != null)
                return false;
        }
        else if (!this.doctorName.equals(other.doctorName))
            return false;
        if (this.deleated == null) {
            if (other.deleated != null)
                return false;
        }
        else if (!this.deleated.equals(other.deleated))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.patientName == null) ? 0 : this.patientName.hashCode());
        result = prime * result + ((this.dateTime == null) ? 0 : this.dateTime.hashCode());
        result = prime * result + ((this.doctorName == null) ? 0 : this.doctorName.hashCode());
        result = prime * result + ((this.deleated == null) ? 0 : this.deleated.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Appointments (");

        sb.append(id);
        sb.append(", ").append(patientName);
        sb.append(", ").append(dateTime);
        sb.append(", ").append(doctorName);
        sb.append(", ").append(deleated);

        sb.append(")");
        return sb.toString();
    }
}
