/*
 * This file is generated by jOOQ.
 */
package database;


import database.tables.Appointments;
import database.tables.records.AppointmentsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppointmentsRecord> KEY_APPOINTMENTS_PRIMARY = Internal.createUniqueKey(Appointments.APPOINTMENTS, DSL.name("KEY_appointments_PRIMARY"), new TableField[] { Appointments.APPOINTMENTS.ID }, true);
}
